from flask import Flask, render_template, jsonify
import json
import os
from datetime import datetime
from config import config, DevelopmentConfig

app = Flask(__name__)

# Load configuration
env = os.environ.get('FLASK_ENV', 'development')
app.config.from_object(config.get(env, DevelopmentConfig))

# Path to stock data
DATA_DIR = app.config.get('DATA_DIR')
DATA_FILE = app.config.get('DATA_FILE')


def load_stock_data():
    """Load stock data from JSON file generated by Top_Stocks.py"""
    if os.path.exists(DATA_FILE):
        with open(DATA_FILE, 'r') as f:
            return json.load(f)
    return None


@app.route('/')
def index():
    """Render main dashboard"""
    data = load_stock_data()
    if not data:
        return render_template('index.html', 
                             error="No stock data available. Run Top_Stocks.py first.")
    return render_template('index.html', data=data)


@app.route('/api/stock-data')
def get_stock_data():
    """API endpoint to get stock data"""
    data = load_stock_data()
    if not data:
        return jsonify({'error': 'No data available'}), 404
    return jsonify(data)


@app.route('/api/refresh')
def refresh_data():
    """Refresh stock data from JSON file"""
    data = load_stock_data()
    if not data:
        return jsonify({'error': 'No data available'}), 404
    return jsonify({
        'success': True,
        'timestamp': data.get('timestamp'),
        'message': 'Data refreshed successfully'
    })


if __name__ == '__main__':
    print("=" * 70)
    print("Stock Tracker Flask Dashboard")
    print("=" * 70)
    print("Starting Flask server on http://localhost:5000")
    print("Make sure to run Top_Stocks.py first to generate data.")
    print("=" * 70)
    app.run(debug=True, port=5000)
