from flask import Flask, render_template, jsonify
import json
import os
import sys
from datetime import datetime
from config import config, DevelopmentConfig

# Add parent directory to path so we can import data_generator
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from data_generator import generate_stock_data, save_stock_data

app = Flask(__name__)

# Load configuration
env = os.environ.get('FLASK_ENV', 'development')
app.config.from_object(config.get(env, DevelopmentConfig))

# Path to stock data
DATA_DIR = app.config.get('DATA_DIR')
DATA_FILE = app.config.get('DATA_FILE')


def load_stock_data():
    """Load stock data from JSON file generated by Top_Stocks.py"""
    if os.path.exists(DATA_FILE):
        with open(DATA_FILE, 'r') as f:
            return json.load(f)
    return None


@app.route('/')
def index():
    """Render main dashboard"""
    data = load_stock_data()
    if not data:
        return render_template('index.html', 
                             error="No stock data available. Run Top_Stocks.py first.")
    return render_template('index.html', data=data)


@app.route('/api/stock-data')
def get_stock_data():
    """API endpoint to get stock data"""
    data = load_stock_data()
    if not data:
        return jsonify({'error': 'No data available'}), 404
    return jsonify(data)


@app.route('/api/refresh')
def refresh_data():
    """Refresh stock data by regenerating from scratch"""
    try:
        print("\n" + "="*70)
        print("REFRESH TRIGGERED FROM FLASK")
        print("="*70)
        
        # Generate fresh stock data (silent mode for web requests)
        data = generate_stock_data(verbose=False)
        
        # Save to file
        output_file = save_stock_data(data, DATA_DIR)
        
        print(f"✓ Data refreshed and saved to {output_file}")
        print("="*70 + "\n")
        
        return jsonify({
            'success': True,
            'timestamp': data.get('timestamp'),
            'message': 'Stock data refreshed successfully',
            'topMovers': data.get('topMovers', {}).get('symbols', []),
            'watchlist': data.get('watchlist', {}).get('symbols', [])
        }), 200
    except Exception as e:
        error_msg = f"Error refreshing data: {str(e)}"
        print(f"✗ {error_msg}")
        return jsonify({
            'success': False,
            'error': error_msg
        }), 500


if __name__ == '__main__':
    print("=" * 70)
    print("Stock Tracker Flask Dashboard")
    print("=" * 70)
    print("Starting Flask server on http://localhost:5000")
    print("Make sure to run Top_Stocks.py first to generate data.")
    print("=" * 70)
    app.run(debug=True, port=5000)
